In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3, random_state=5)

In [9]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9648148148148148

In [10]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9851851851851852

In [11]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9703703703703703

**K FOLD**

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [16]:
get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test)

0.9648148148148148

In [18]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [32]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [33]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [34]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [35]:
scores_rf

[0.9215358931552587, 0.9515859766277128, 0.9248747913188647]

In [36]:
from sklearn.model_selection import cross_val_score

In [39]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [38]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.92777778, 0.89722222, 0.95821727, 0.95543175, 0.93036212])